import { MigrationInterface, QueryRunner } from 'typeorm';

export class Projects1738148819787 implements MigrationInterface {
  name = 'Projects1738148819787';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "projects" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
                                "title" character varying NOT NULL, 
                                "description" character varying NOT NULL, 
                                "companyId" integer NOT NULL, 
                                "createdAt" TIMESTAMP NOT NULL DEFAULT now(), 
                                "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), 
                                "deletedAt" TIMESTAMP, 
                                "isActive" boolean NOT NULL DEFAULT true, 
                                CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `ALTER TABLE "projects" ADD CONSTRAINT "FK_87fa45e3f4517658b98e5c55b9c" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(`
    INSERT INTO "projects" (title, description, "companyId") VALUES ('Project 1', 'Project 1 description', 1);
    INSERT INTO "projects" (title, description, "companyId") VALUES ('Project 2', 'Project 2 description', 1);
    INSERT INTO "projects" (title, description, "companyId") VALUES ('Project 3', 'Project 1 description', 1);
    INSERT INTO "projects" (title, description, "companyId") VALUES ('Project 1', 'Project 1 description', 2);
    INSERT INTO "projects" (title, description, "companyId") VALUES ('Project 2', 'Project 2 description', 2);
    INSERT INTO "projects" (title, description, "companyId") VALUES ('Project 3', 'Project 1 description', 2);
    INSERT INTO "projects" (title, description, "companyId") VALUES ('Project 1', 'Project 1 description', 3);
    INSERT INTO "projects" (title, description, "companyId") VALUES ('Project 2', 'Project 2 description', 3);
    INSERT INTO "projects" (title, description, "companyId") VALUES ('Project 3', 'Project 1 description', 3);
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "projects" DROP CONSTRAINT "FK_87fa45e3f4517658b98e5c55b9c"`,
    );
    await queryRunner.query(`DROP TABLE "projects"`);
  }
}
